# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e50ad90a7bc8de7fa4a30c2d503bc168e12ee506aca72bde10d434230d12f13f7295f4f478574e7195cade96c5237a62fee8d6bdf3ba0776826cfb9e5bc3750

test:
  secret_key_base: caabc910da9f43e1b1c0da85434837b1aa8a2003a9c07fa0b43d1ec18aa5166c3641022f1b7a5927bd5490e8500844c92f4c8a17f1696d1e5d1da74659adf052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
